name: release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build archlinux package
        uses: countstarlight/arch-makepkg-action@master
        with:
          packages: >
            p7zip
            wine
            wine-mono
            wine-gecko
            xorg-xwininfo
            wqy-microhei
            lib32-alsa-lib
            lib32-alsa-plugins
            lib32-libpulse
            lib32-openal
            lib32-mpg123
            lib32-libldap
          scripts: "makepkg && ./gen.sh -m"
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: deepin-wine-wechat*.pkg*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}